# Generated by Django 4.2.7 on 2025-09-09 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ner_labeler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_overlapping_annotations", models.BooleanField(default=True)),
                ("require_all_labels", models.BooleanField(default=False)),
                ("owner_id", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=ner_labeler.models.generate_uuid,
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Identifier"),
                            ("quasi", "Quasi Identifier"),
                            ("default", "Default"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("annotator_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ner_labeler.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=ner_labeler.models.generate_uuid,
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("text", models.TextField()),
                ("labels", models.JSONField(default=list)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Identifier"),
                            ("quasi", "Quasi Identifier"),
                            ("default", "Default"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("overlapping", models.BooleanField(default=False)),
                ("related_annotations", models.JSONField(default=list)),
                ("entity_id", models.CharField(blank=True, max_length=36, null=True)),
                ("relationships", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="ner_labeler.task",
                    ),
                ),
            ],
            options={
                "db_table": "annotations",
                "ordering": ["start", "end"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("background", models.CharField(default="#999999", max_length=7)),
                ("hotkey", models.CharField(blank=True, max_length=1, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("example", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="ner_labeler.project",
                    ),
                ),
            ],
            options={
                "db_table": "labels",
                "ordering": ["sort_order", "value"],
                "unique_together": {("project", "value"), ("project", "hotkey")},
            },
        ),
    ]
