# Generated by Django 4.2.7 on 2025-09-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ner_labeler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="ner_labeler.project",
            ),
        ),
    ]
