# Generated by Django 4.2.7 on 2025-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner_labeler", "0003_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extracted_labels",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
