# Generated by Django 4.2.7 on 2025-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner_labeler", "0004_uploadedfile_extracted_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pre_annotations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
